### ISSUE TITLE
Support SAM2

### ISSUE THREAD

**Issue by ksugar** [ksugar/samapi#21]
Add endpoints for SAM2.
- Image predictor
- Video predictor

https://ai.meta.com/research/publications/sam-2-segment-anything-in-images-and-videos/
https://github.com/facebookresearch/segment-anything-2

**Comment by kess-one** [comment]
Please excuse my ignorance, could you please provide a more detailed description of how to implement this new model?

Thanks so much!

**Comment by ksugar** [comment]
Hi @kess-one, it's done now. https://github.com/ksugar/samapi/issues/21

**Comment by ksugar** [comment]
v0.5.0 now supports SAM2. https://github.com/ksugar/samapi/issues/21
