### ISSUE TITLE
Provide a path for model installation

### ISSUE THREAD

**Issue by StRigaud** [ksugar/samapi#27]
Is there an option (or could it be added) to give a path where to download and look for the models? Instead of always installing them into a hidden folder at the user profile home directory?

**Comment by ksugar** [comment]
Hi @StRigaud , thank you for the question.
The environment variable `SAMAPI_ROOT_DIR` can be used for that!

https://github.com/ksugar/samapi/blob/914703a61328cde291816f80363d0fa0402115bb/src/samapi/main.py#L60

I will include that information to README.
Please let me know if you have any further questions.

**Comment by StRigaud** [comment]
Hi @ksugar, thanks for the tips! That's what I needed.
