### ISSUE TITLE
Introduce MobileSAM

### ISSUE THREAD

**Issue by ksugar** [ksugar/samapi#6]
MobileSAM is much faster than the original SAM, keeping the output quality.

https://github.com/ChaoningZhang/MobileSAM

Image Encoder | Original SAM | MobileSAM
-- | -- | --
Paramters | 611M | 5M
Speed | 452ms | 8ms

Mask Decoder | Original SAM | MobileSAM
-- | -- | --
Paramters | 3.876M | 3.876M
Speed | 4ms | 4ms

Whole Pipeline (Enc+Dec) | Original SAM | MobileSAM
-- | -- | --
Paramters | 615M | 9.66M
Speed | 456ms | 12ms

**Comment by mezwick** [comment]
Excited to see this planned!

I noticed also this repo and wondered if it could be implemented with the plugin. Not sure if fastsam or mobilesam have merits over the other
https://github.com/CASIA-IVA-Lab/FastSAM

**Comment by ksugar** [comment]
It's released with [v0.3.0](https://github.com/ksugar/samapi/releases/tag/v0.3.0).
